-- Private source records used to calculate small-market trends.
-- RLS is enabled with no public policy: site visitors cannot query individual sales.

create table if not exists public.market_sale_records (
  id bigint generated by default as identity primary key,
  city text not null,
  mls_number text not null,
  sold_date date not null,
  sold_price numeric not null check (sold_price > 0),
  list_price numeric,
  original_list_price numeric,
  sale_to_list_ratio numeric,
  days_on_market integer,
  property_sub_type text not null,
  is_single_family boolean not null default false,
  is_fractional boolean not null default false,
  eligible_for_market_stats boolean not null default true,
  source text not null default 'mls_grid_export',
  imported_at timestamptz not null default now(),
  unique (city, mls_number)
);

create index if not exists market_sale_records_city_sold_date_idx
  on public.market_sale_records (city, sold_date);

create index if not exists market_sale_records_market_stats_idx
  on public.market_sale_records (city, sold_date)
  where eligible_for_market_stats and is_single_family;

alter table public.market_sale_records enable row level security;
